// build-recs.mjs — Stage C: bake the workflow's scores into recs.js (window.RECS).
//
// Inputs:
//   recs-raw.json   — the workflow return value: { technical:[{idx,...}], socials:[{idx,...}] }
//   candidates.json — maps each scored idx back to the real schedule session ids
//   socials.json    — maps social idx back to session ids
// Output:
//   recs.js — window.RECS, keyed by session id, plus default tuning config + track meta.
//
// Run: node build-recs.mjs

import { readFileSync, writeFileSync, existsSync } from "node:fs";

if (!existsSync("./recs-raw.json")) {
  console.error("recs-raw.json not found — save the workflow output to recs-raw.json first.");
  process.exit(1);
}

const raw = JSON.parse(readFileSync("./recs-raw.json", "utf8"));
const candidates = JSON.parse(readFileSync("./candidates.json", "utf8")).candidates;
const socialsSrc = JSON.parse(readFileSync("./socials.json", "utf8")).socials;

const talks = {};
let mapped = 0, missing = 0;
for (const r of raw.technical || []) {
  const cand = candidates[r.idx];
  if (!cand) { missing++; continue; }
  const rec = {
    relevance: r.relevance, depth: r.depth, novelty: r.novelty, goalFit: r.goalFit,
    creativeAppeal: r.creativeAppeal, format: r.format,
    track: r.track, trackName: r.trackName,
    keywords: r.keywords || [], rationale: r.rationale || "", confidence: r.confidence || "med",
  };
  for (const id of cand.ids) { talks[id] = rec; mapped++; }
}

const socials = {};
for (const r of raw.socials || []) {
  const src = socialsSrc[r.idx];
  if (!src) continue;
  socials[src.id] = { networkingValue: r.networkingValue, worthIt: !!r.worthIt, rationale: r.rationale || "" };
}

// ── track taxonomy + budget (from tracks.json — the forker's priority areas) ─
const tracksSrc = JSON.parse(readFileSync("./tracks.json", "utf8"));
const TRACK_META = {};
const trackBudget = {};
for (const [k, v] of Object.entries(tracksSrc)) {
  if (k.startsWith("_")) continue;            // skip _comment
  TRACK_META[k] = { name: v.name, hue: v.hue };
  if (k !== "none") trackBudget[k] = v.budget || 0;
}

// ── default tuning config (the live knobs start here) ──────────────────────
const config = {
  // dimension weights — relevance is doubled inside the score formula per the brief
  weights: { relevance: 1.0, depth: 1.0, novelty: 1.0, goalFit: 1.0 },
  adventurousness: 0.35,            // 0 = strictly technical, 1 = lots of creative left-field
  formatBonus: { "war-story": 1.0, mixed: 0, tutorial: -1.5, hype: -3.0, unknown: -0.5 },
  trackBudget,                       // weekly slot targets, per track, from tracks.json
};

const out = { config, trackMeta: TRACK_META, talks, socials };
writeFileSync(
  "./recs.js",
  "/* AUTO-GENERATED by build-recs.mjs — do not edit by hand. */\n" +
    "window.RECS = " + JSON.stringify(out) + ";\n",
);

const tierCounts = {};
Object.values(talks).forEach((r) => {
  const s = r.relevance * 2 + r.depth + r.novelty + r.goalFit;
  const tier = s >= 18 ? "must" : s >= 13 ? "strong" : s >= 8 ? "maybe" : "skip";
  tierCounts[tier] = (tierCounts[tier] || 0) + 1;
});
console.log(`recs.js written — ${mapped} session ids scored (${missing} idx unmapped), ${Object.keys(socials).length} socials.`);
console.log("  rough tiers (unweighted):", JSON.stringify(tierCounts));
